// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujvjjzhhkzhjtesielud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqdmpqemhoa3poanRlc2llbHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDkyMTMsImV4cCI6MjA2Nzc4NTIxM30.x4dhFhG9kSU1bWRFZq99eMwGV1d7lGoqyMlcu4SoW5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});